### ISSUE TITLE
Toggle Window

### ISSUE THREAD

**Issue by hadiplays** [ufosc/Lunch_Buddies#3]
#### This page will be accessed after the user logs in or signs up. 

<p align="center">
    <img width="" height="" src="https://user-images.githubusercontent.com/100600064/198373782-2fd4597a-f610-42ac-bf1a-138f511d6e0c.png">
</p>

**Comment by prayujt** [comment]
Page should be accessed as a popup after the user logs in and then clicks the toggle window button
