### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by hadiplays** [ufosc/Lunch_Buddies#4]
- Home page should be accessed after the "Start Page". 
- Users should first see the "Home Normal" page. 
- "Home Bio" page must have the users profile picture on the grey circle with all their biography info below it.

<p align="center">
    <img width="" height="" src="https://user-images.githubusercontent.com/100600064/198375094-cff4a059-0ef5-4c69-a182-d39246e772eb.png">
</p>

**Comment by prayujt** [comment]
Main Page will be accessed after the toggle window is submitted and the user has entered the pool of available people.

**Comment by prayujt** [comment]
Home Page has a button to open the "toggle window". Before user is "toggled" on, home page displays the user's profile in the same manner. Once toggled on, will display cards of other available users.
